### PR TITLE
Used built in Zotero localisation for item type

### LINKED ISSUE #65: Ability to access the localized values for fields
I'm interested in lowering the barrier to good knowledge management for non-english speakers.

In this respect, it would be great to be able to access the localized values for fields [such as ItemTypes](https://github.com/zotero/zotero/blob/fd94d731d4ea79ed35db65ac10e0f2c6ccb26637/chrome/locale/fr-FR/zotero/zotero.properties#L403).

Also, links to english terms make little sense to non-english speakers.
For instance, `[[Video recording]]` does'nt make much sense within in a collection of notes in French, as opposed to `[[Enregistrement vidéo]]`.

Cheers

### PR DESCRIPTION
**Pull request by PhilipMottershead**
Added localization support for ItemTypes to fix #65

Further work is need to localise parts of the output

### CODE REVIEW

**Comment by argenos** [comment]
This should definitely be optional!

**Comment by PhilipMottershead** [comment]
So a option in the menu if they wan't tags to folllow the system locale for item tags?

**Comment by PhilipMottershead** [comment]
As if a translation is missing it will default to english this will only work if they change thier locale in  which I expect they would want their native language to be exported

**Comment by argenos** [comment]
yeah, I think a hidden preference for this would suffice. Something 
along the lines of `extensions.mdnotes.localize_fields` (true/false).

**Pull request closed without merging**
